### ISSUE TITLE
Camera 0 error and Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by ykn96** [HowieMa/DeepSORT_YOLOv5_Pytorch#8]
Hi there. I have tried running the programme on 2 seperate instances and have encountered these errors. I have made sure to have connected the webcam (the only webcam too), so that it takes --cam 0 correctly.

Here are the terminal outputs
```
python3 main.py --cam 0 --display
Namespace(agnostic_nms=False, augment=False, cam=0, classes=[0], conf_thres=0.5, config_deepsort='./configs/deep_sort.yaml', device='', display=True, display_height=600, display_width=800, fourcc='mp4v', frame_interval=2, img_size=640, input_path='input_480.mp4', iou_thres=0.5, save_path='output/', save_txt='output/predict/', weights='yolov5/weights/yolov5s.pt')
Initialize DeepSORT & YOLO-V5
Using CPU

Using webcam 0
Done..
Camera ...
Done. Create output file  output/results.mp4
Illegal instruction (core dumped)
````

And in another instance, I have a different error citing camera error
```
python3 main.py --cam 0 --display
Namespace(agnostic_nms=False, augment=False, cam=0, classes=[0], conf_thres=0.5, config_deepsort='./configs/deep_sort.yaml', device='', display=True, display_height=600, display_width=800, fourcc='mp4v', frame_interval=2, img_size=640, input_path='input_480.mp4', iou_thres=0.5, save_path='output/', save_txt='output/predict/', weights='yolov5/weights/yolov5s.pt')
Initialize DeepSORT & YOLO-V5
Using CPU

Using webcam 0
Done..
Camera ...
[ WARN:0] global /tmp/pip-req-build-tpkxoqhj/opencv/modules/videoio/src/cap_v4l.cpp (1001) tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
Traceback (most recent call last):
  File "main.py", line 259, in <module>
    with VideoTracker(args) as vdo_trk:
  File "main.py", line 75, in __enter__
    assert ret, "Error: Camera error"
AssertionError: Error: Camera error
````
The camera error occured right after the illegal instruction (core dumped) episode. When the programme was first run, the windows for the display could be open, but there is no video feed, and it just stops responding in Ubuntu (window goes greyscale) 

Error title is :
``` 
python3.8 crashed with SIGILL in exec_blas()
 ````

If required, my device's techncial specs
DJI Manifold 2G (Nvidia Jetson TX2)
ARMv8 Processor rev 3 (v8l) × 4 ARMv8 Processor rev 0 (v8l) × 2 
NVIDIA Tegra X2 (nvgpu)/integrated
8GB ram, Ubuntu 18.04 LTS

**Comment by ykn96** [comment]
Hello i have re-tried after my system crashed thinking it was a hardware problem

I encountered this, similar problem after fixing the hardware issues and driver isssues. 
```
python3 main.py --cam 0 --display
Namespace(agnostic_nms=False, augment=False, cam=0, classes=[0], conf_thres=0.5, config_deepsort='./configs/deep_sort.yaml', device='', display=True, display_height=600, display_width=800, fourcc='mp4v', frame_interval=2, img_size=640, input_path='input_480.mp4', iou_thres=0.5, save_path='output/', save_txt='output/predict/', weights='yolov5/weights/yolov5s.pt')
Initialize DeepSORT & YOLO-V5
Using CPU

Using webcam 0
Done..
Camera ...
Done. Create output file  output/results.mp4
Illegal instruction (core dumped)
```` 
System specs: (minor changes)
DJI Manifold 2G (Nvidia Jetson TX2)
ARMv8 Processor rev 3 (v8l) × 4 ARMv8 Processor rev 0 (v8l) × 2
NVIDIA Tegra X2 (nvgpu)/integrated
8GB ram, Ubuntu 16.04 LTS
